name: ginkgo_tv
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  window_manager:
  sentry_flutter:
  lottie:
  bot_toast:
  double_back_to_close:
  flutter_launcher_icons:
  another_flutter_splash_screen:
  flutter_context_menu:
  file_picker:
  fialogs:
  get:
  flutter_plugin_android_lifecycle: ^2.0.23


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/Netflix.json
    - assets/lottie/WatchTV.json
    - assets/sound/Netflix.wav
    - assets/icon/icon.png
    - assets/icon/image.png
    - assets/gif/splash.gif
    